### ISSUE TITLE
请教大佬在Jetson NX上运行时提示：only integer scalar arrays can be converted to a scalar index

### ISSUE THREAD

**Issue by ynioba** [hpc203/yolov5-lite-onnxruntime#5]
Jetson NX 4.6，onnxruntime 1.9，python 3.6.9 
具体错误信息如下：
Traceback (most recent call last):
  File "main.py", line 137, in <module>
    srcimg = net.detect(srcimg)
  File "main.py", line 121, in detect
    srcimg = self.postprocess(srcimg, outs, (newh, neww, top, left))
  File "main.py", line 82, in postprocess
    box = boxes[i]
TypeError: only integer scalar arrays can be converted to a scalar index

我尝试把boxes用numpy来转为array也不行。

**Comment by ynioba** [comment]
通过print(boxes)，发现i是个数组，如果改为数组0元素的值就可以了。具体改动如下：
 第78行，i = i[0]  #if isinstance(i, (tuple,list)) else i 
屏蔽掉后面的if isinstance(i, (tuple,list)) else i ，另外这句我也没看懂。能说说吗？
